version: '1'
services:
  phoenix:
    build: .
    entrypoint: ./phoenix/phoenix
    ports:
      - "9001:9000"
    links:
      - users_microservice
      - config
      - contracts
      - db
    env_file:
      - .env
  users_microservice:
    build: .
    entrypoint: ./users_microservice/users_microservice/
    ports:
      - "9011:9010"
    links:
      - phoenix
      - config
      - contracts
      - bd